version: "2"
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
    - "27017"
  demax-server:
    build:
      context: .
      dockerfile: 'Dockerfile-prod'
    ports:
    - '3000:3000'
    depends_on:
    - mongodb
  demax-client:
    build:
      context: "./demax-client"
      dockerfile: 'Dockerfile-nginx'
    ports:
    - '8080:8080'
