version: "3"
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
    - "27017"
    volumes:
    - /data/mongodb:/bitnami
  demax-server:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
    - '3000:3000'
    depends_on:
    - mongodb
  demax-client:
    build:
      context: "./demax-client"
      dockerfile: 'Dockerfile'
    ports:
    - '3001:3001'
volumes:
  mongodb_data:
    driver: local
