FROM node:alpine
LABEL maintainer="jeremias.hillerberg@esss.se"
ENV no_proxy "localhost, 127.0.0.1"
RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
RUN apk --update add openjdk7-jre
COPY package.json /usr/src/app/package.json
WORKDIR /usr/src/app
RUN npm install --save
COPY . /usr/src/app
CMD ["sh", "./local-test.sh"]
