version: "3"
services:
  demax-server:
    build:
      context: .
      dockerfile: 'Dockerfile-prod'
    ports:
      - '3000:3000'
  demax-client:
    build:
      context: "./demax-client"
      dockerfile: 'Dockerfile-prod'
    ports:
      - '4200:443'
