FROM node:alpine
LABEL maintainer="jeremias.hillerberg@esss.se"
#ENV http_proxy "http://172.18.12.30:8123"
#ENV https_proxy $http_proxy
ENV no_proxy "localhost, 127.0.0.1"

ENV DEV_APP_PORT = 3000
ENV DEV_DB_HOST = 'localhost'
ENV DEV_DB_PORT = 27017
ENV DEV_DB_NAME = 'ess'

#RUN npm config set proxy  $http_proxy
#RUN npm config set https-proxy  $http_proxy
RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
COPY package.json /usr/src/app/package.json
WORKDIR /usr/src/app
RUN npm install
COPY . /usr/src/app
EXPOSE 3000
CMD ["sh", "wait.sh"]
