version: "3"
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
    - "27017"
    volumes:
    - mongodb_data:/bitnami
  demax-server:
    build:
      context: .
      dockerfile: 'Dockerfile-dev'
    ports:
    - '3000:3000'
    depends_on:
    - mongodb
  demax-client:
    build:
      context: "./client"
      dockerfile: 'Dockerfile-dev'
    ports:
    - '8080:8080'
volumes:
  mongodb_data:
    driver: local
