version: "2"
services:
  mongodb:
    image: 'mongo:latest'
    ports:
    - "27017"
    mem_limit: 500m
  demax-server:
    build:
      context: .
      dockerfile: 'Dockerfile-prod'
    mem_limit: 500m
    ports:
    - '3000:3000'
    depends_on:
    - mongodb
  demax-client:
    build:
      context: "./demax-client"
      dockerfile: 'Dockerfile-prod'
    mem_limit: 500m
    ports:
    - '8080:8080'
