version: "3"
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
    - "27017"
    volumes:
    - /data/mongodb:/bitnami
  demax-server:
    image: 'essdmscdm/demax-server:latest'
    ports:
    - '3000:3000'
    depends_on:
    - mongodb
    volumes:
    - /data/mongodb/files:/usr/src/app/files
  demax-client:
    image: 'essdmscdm/demax-client:latest'
    ports:
    - '8080:8080'
volumes:
  mongodb_data:
    driver: local
