version: "3"
volumes:
  mongodb_data:
    driver: local
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
    - "27017"
    volumes:
    - 'mongodb_data:/bitnami'
  demax-server:
    build:
      context: .
      dockerfile: 'Dockerfile-prod'
    ports:
      - '8080:8080'
    depends_on:
    - mongodb
  demax-client:
    build:
      context: "./demax-client"
      dockerfile: 'Dockerfile-prod'
    ports:
      - '4200:443'
