FROM node:alpine
LABEL maintainer="jeremias.hillerberg@esss.se"
ENV no_proxy "localhost, 127.0.0.1"
RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
RUN apt-get update && apt-get install -y default-jdk
COPY package.json /usr/src/app/package.json
RUN npm install --save
COPY . /usr/src/app
WORKDIR /usr/src/app
CMD ["sh", "./local-test.sh"]