FROM node:alpine
LABEL maintainer="jeremias.hillerberg@esss.se"
ENV no_proxy "localhost, 127.0.0.1"
RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
RUN apk --update add openjdk7-jre
RUN npm config set unsafe-perm true
COPY package.json /usr/src/app/package.json

WORKDIR /usr/src/app

RUN npm install
RUN npm -i install pm2 -g

ENV PM2_PUBLIC_KEY bsdqsp68s8fmpt0
ENV PM2_SECRET_KEY 11hpeh8h86sdh9v

RUN pm2 link 11hpeh8h86sdh9v bsdqsp68s8fmpt0 DEMAX_SERVER
COPY . /usr/src/app

EXPOSE 3000
RUN gcloud app config
CMD ["sh", "demax-server/CI/scripts/pm2.sh"]
