FROM node:alpine
LABEL maintainer="jeremias.hillerberg@esss.se"
ENV no_proxy "localhost, 127.0.0.1"

ENV PM2_PUBLIC_KEY bsdqsp68s8fmpt0
ENV PM2_SECRET_KEY 11hpeh8h86sdh9v

RUN npm config set registry http://registry.npmjs.org/
RUN npm config set strict-ssl false
RUN apk --update add openjdk7-jre
RUN npm install pm2 -g

COPY package.json /usr/src/app/package.json

WORKDIR /usr/src/app

RUN npm install

COPY . /usr/src/app

EXPOSE 3000
CMD ["sh", "./CI/scripts/sleep.sh"]
CMD ["npm", "run", "pm2"]
