version: "3"
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
    - "27017"
  demax-server:
    build:
      context: ../..
      dockerfile: '../dockerfiles/Dockerfile-test-local'
    ports:
    - '3000:3000'
    depends_on:
    - mongodb