version: "3"
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
    - "27017"
    volumes:
    - /data/mongodb:/bitnami
  demax-server:
    build:
      context: ../..
      dockerfile: '../dockerfiles/Dockerfile-pm2'
    ports:
    - '3000:3000'
    depends_on:
    - mongodb
    volumes:
    - /data/mongodb/files:/usr/src/app/files
  demax-client:
    build:
      context: "../../demax-client"
      dockerfile: 'Dockerfile'
    ports:
    - '8080:8080'
volumes:
  mongodb_data:
    driver: local
