version: "3"
services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
    - "27017"
  demax-server:
    build:
      context: ../..
      dockerfile: './CI/dockerfiles/Dockerfile-dev'
    ports:
    - '3000:3000'
    depends_on:
    - mongodb
  demax-client:
    build:
      context: "../../demax-client"
      dockerfile: 'Dockerfile-dev'
    ports:
    - '8080:8080'
volumes:
  mongodb_data:
    driver: local
